services:
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/bitnami/postgresql

volumes:
  db_data: